# Environment secrets for Streamlit Cloud
# Add these as secrets in your Streamlit Cloud dashboard

# OpenAI Configuration
OPENAI_API_KEY = "your_openai_api_key_here"

# Supabase Configuration  
SUPABASE_URL = "your_supabase_url_here"
SUPABASE_ANON_KEY = "your_supabase_anon_key_here"

# RAG System Configuration
SIMILARITY_THRESHOLD = 0.2
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
LOG_LEVEL = "INFO"
MAX_FILE_SIZE_MB = 10
