name: Deploy Python app to Azure Web App - askmydocs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: askmydocs-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build a slim deploy bundle (avoid venvs, caches, logs, zips, etc.)
      - name: Build deploy bundle
        run: |
          set -e
          rm -rf deploy
          mkdir deploy
          rsync -a . deploy \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '.gitignore' \
            --exclude '.gitattributes' \
            --exclude '.env' \
            --exclude '*.log' \
            --exclude '*.zip' \
            --exclude 'antenv' \
            --exclude 'venv' \
            --exclude '.venv' \
            --exclude 'env' \
            --exclude '__pycache__' \
            --exclude '.python_packages' \
            --exclude 'node_modules'
            --exclude '.devcontainer'
          # Ensure correct runtime is present (3.12)
          if [ ! -f deploy/runtime.txt ]; then echo 'python-3.12' > deploy/runtime.txt; fi
          # Make startup executable if present
          if [ -f deploy/startup.sh ]; then chmod +x deploy/startup.sh; fi

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_546DB718B6B54D82BBA2FE579F0F808C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E3BB5974703147E1A26C4B4E3F50B9C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B26783C90B6E4A2FA6186547B80688B6 }}

      - name: Deploy to Azure Web App (OneDeploy)
        uses: azure/webapps-deploy@v3
        with:
          app-name: askmydocs
          slot-name: Production
          package: ./deploy
